[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "alphalab"
version = "0.1.0"
dependencies = ["numpy>=1.20.0", "pandas>=1.3.0"]

[tool.setuptools.package-dir]
"" = "src"

[tool.pytest.ini_options]
pythonpath = ["src"]